global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequency: 2.0
  static_map: true
  footprint_padding: 0.5
  inflation_radius: 0.75
  footprint: [[0.125,0.45], [0.125,-0.45], [-0.125,-0.45], [-0.125,0.45]]
  
