base_global_planner: navfn/NavfnROS
base_local_planner: TebLocalPlannerROS
clearing_rotation_allowed: true
conservative_reset_dist: 3.0
controller_frequency: 20.0
controller_patience: 1.0
max_planning_retries: -1
oscillation_distance: 0.5
oscillation_timeout: 0.0
planner_frequency: 20.0
planner_patience: 1.0
recovery_behavior_enabled: true
restore_defaults: false
shutdown_costmaps: false

