# Paramater settings for Evo-Ros2
# GAS 08-16-2018

# Common Params
SERVER_IP_ADDR: '127.0.0.1'
GENOME_PORT: 5000
RESULT_PORT: 5010
DEBUG: True
EVO_ROS_COMM_TOPIC: 'evo_ros2_int_comms'


# Software Manager
software_manager:
   # Launch files: ['pkg', 'launch_file.launch']
   WORLD_LAUNCH_FILE: ['msu_autorally_helper', 'spawn_gazebo_world.launch']
   PLATFORM_LAUNCH_FILE: ['msu_autorally_helper','spawn_autorally_platform.launch']
   SIM_MANAGER_LAUNCH_FILE: ['evo_ros2', 'sim_manager.launch']

   
 # Simulation Manager Script
sim_manager:
   #MISSION_LAUNCH_FILE: ['msu_autorally_helper','way_point_publisher.launch']
   MISSION_LAUNCH_FILE: ['msu_autorally_helper','speed_signal_publisher.launch']
   MAX_SIM_TIME: 540 # simulation seconds a simulation is allowed to run before ending 
