# Genome Mapping for list of floats from Evo Search Algorithm
# GAS 08-16-2018

GENOME_MAPPING: ['/base_controller_nodelet/IMax', '/base_controller_nodelet/KD', '/base_controller_nodelet/KI', '/base_controller_nodelet/KP']
GENOME_WEIGHTS: [10.0, 10.0, 10.0, 10.0]
